
listen: ":8080"
language: zh-CN

tmdb:
  api_key: "5640d0f3eea1e20a18d3a1f150b3a1ef"

libraries:
  - name: "Movies"
    path: "/Volumes/data/Videos/Movies"

  - name: "TV Shows"
    path: "/Volumes/data/Videos/TV Shows"

  - name: "Music"
    path: "/Volumes/data/Music"

  # - name: "Photos"
  #   path: "/Volumes/data/Pictures"

  # - name: "Software"
  #   path: "/Volumes/software"
  
  - name: "Books"
    path: "/Volumes/data/Documents/books/books"

  # - name: "Japanese AV"
  #   path: "/Volumes/data/Videos/JapaneseAV"