
listen: ":8088"

data: ""

storages:
  - id: data
    name: Data
    type: local
    path: /Volumes/data

libraries:
  - id: movies
    name: Movies
    type: movies
    sources:
      - storage: data
        path: Videos/Movies

  - id: tvshows
    name: TV Shows
    type: tv
    sources:
      - storage: data
        path: Videos/TV Shows

  - id: music
    name: Music
    type: music
    sources:
      - storage: data
        path: Music

  - id: photos
    name: Photos
    type: photos
    sources:
      - storage: data
        path: Pictures

  - id: documents
    name: Documents
    type: files
    sources:
      - storage: data
        path: Documents
