
listen: ":8080"
language: zh-CN

tmdb:
  api_key: "5640d0f3eea1e20a18d3a1f150b3a1ef"

libraries:
  - name: "Movies"
    slug: "movies"
    path: "/Volumes/data/Videos/Movies"

  - name: "TV Shows"
    slug: "tvshows"
    path: "/Volumes/data/Videos/TV Shows"

  - name: "Music"
    slug: "music"
    path: "/Volumes/data/Music"

  - name: "Photos"
    slug: "photos"
    path: "/Volumes/data/Pictures"

  # - name: "Software"
  #   slug: "software"
  #   path: "/Volumes/software"

  - name: "Books"
    slug: "books"
    path: "/Volumes/data/Documents/books/books"

  # - name: "Japanese AV"
  #   slug: "jav"
  #   path: "/Volumes/data/Videos/JapaneseAV"