ALTER TABLE storages ADD COLUMN scan_started_at DATETIME;
ALTER TABLE storages ADD COLUMN scan_updated_at DATETIME;
ALTER TABLE storages ADD COLUMN scan_entries INTEGER NOT NULL DEFAULT 0;
ALTER TABLE storages ADD COLUMN scan_files INTEGER NOT NULL DEFAULT 0;
ALTER TABLE storages ADD COLUMN scan_directories INTEGER NOT NULL DEFAULT 0;
ALTER TABLE storages ADD COLUMN scan_estimate INTEGER NOT NULL DEFAULT 0;
ALTER TABLE storages ADD COLUMN scan_error TEXT;
