name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Test
        run: go test ./...
      - name: Build release targets
        run: make build
      - name: Set current date
        if: github.event_name == 'push'
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"
      - name: Upload Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-tag-${{ env.date }}
          name: release-${{ env.date }}
          files: bin/*
          draft: false
